name: Admin Workflow
on: 
    pull_request:
        branches:
            - auth-admin
            - main
    push:
        branches:
            - main
jobs:
    set-up-environment:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1

        - name: Flutter set up
          uses: subosito/flutter-action@v1
          with:
            flutter-version: 3.19
        - name: Clean Build
          run: flutter clean
          working-directory: apps/admin
        
        - name: Getting Dependencies
          run: flutter pub get
          working-directory: apps/admin

        - name: Build Apk Release
          run: flutter build apk --split-per-abi
          working-directory: apps/admin